site_name: DeepOnto
site_author: Yuan He (KRR-Oxford)
site_url: https://krr-oxford.github.io/DeepOnto/
repo_url: https://github.com/KRR-Oxford/DeepOnto
repo_name: KRR-Oxford/DeepOnto

copyright: Copyright &copy; 2021 Yuan He (KRR-Oxford)

# theme: readthedocs
theme:
  name: material
  custom_dir: docs/overrides
  logo: images/favicon_package/safari-pinned-tab.svg
  palette:
    primary: teal
  favicon: images/favicon_package/favicon.ico
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - header.autohide
    - toc.follow
    - content.code.copy
# extra:
#   social:
#     - icon: fontawesome/solid/paper-plane
#       link: mailto:yuan.he@cs.ox.ac.uk

extra:
  # version: 0.5.0
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/deeponto/
    - icon: fontawesome/brands/github
      link: https://github.com/Lawhy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/YuanHe97
  status:
    - new: recently added



nav:
    - GET STARTED: 
      - Introduction: index.md
      - Load an ontology: ontology.md  # basic usage of ontologies, ontology pruning, etc.
      - Changelog: changelog.md
    - TUTORIALS:
      - Verbalise ontology concepts: verbaliser.md
      - Ontology matching with BERTMap & BERTMapLt: bertmap.md
      - Bio-ML specifications: bio-ml.md
      - Subsumption inference with BERTSubs: bertsubs.md
    - PACKAGE REFERENCE:
        - Ontology Processing: 
          - Ontology: deeponto/onto/ontology.md
          - Reasoning: deeponto/onto/reasoning.md
          - Pruning: deeponto/onto/pruning.md
          - Verbalisation: deeponto/onto/verbalisation.md
        - Ontology Alignment:
          - Mapping: deeponto/align/mapping.md
          - BERTMap: deeponto/align/bertmap/index.md
          - LogMap: deeponto/align/logmap/index.md
          - BERTSubs (Inter): deeponto/align/bertsubs/index.md
          - Evaluation: deeponto/align/evaluation.md
        - Subsumption Inference:
          - BERTSubs (Intra): deeponto/subs/bertsubs/index.md
        - Language Model Probing:
          - OntoLAMA: deeponto/probe/ontolama.md
        - Utilities: 
          - Text Utilities: deeponto/utils/text_utils.md
          - File Utilities: deeponto/utils/file_utils.md
          - Logging: deeponto/utils/logging.md
          - Data Utilities: deeponto/utils/data_utils.md
          - Decorators: deeponto/utils/decorators.md



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - include-markdown
  - search
  - autorefs
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]  # search packages in the src folder
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_root_full_path: no
            show_root_toc_entry: false
            members_order: source
            docstring_section_style: table


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js