site_name: DeepOnto
# sit_url: https://krr-oxford.github.io/DeepOnto/
repo_url: https://github.com/KRR-Oxford/DeepOnto

# theme: readthedocs
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - header.autohide
    - toc.follow


nav:
    - GET STARTED: 
      - Introduction: index.md
      - Bio-ML: pages/om_resources.md
    - PACKAGE REFERENCE:
        - Ontology: deeponto/onto/index.md
        - BERTMap: deeponto/align/bertmap/index.md



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

plugins:
  - include-markdown
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: source


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js