model: bertsubs

onto_file: ../ontologies/go.origin.07012022.owl,
label_property:
  - http://www.w3.org/2000/01/rdf-schema#label
  - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
use_one_label: true # true: select only one label

test_subsumption_file: GO/test_subsumptions_r.csv
valid_subsumption_file: GO/valid_subsumptions_r.csv
train_subsumption_file: GO/train_subsumptions_r.csv

prompt:
  prompt_type: isolated # "isolated", "traversal", "path"
  prompt_hop: 1
  prompt_max_subsumptions: 4
  use_sub_special_token: false # true: <SUB>, false: <SEP>
  context_dup: 4
  max_length: 128

batch_size: 32

fine-tune:
  do-fine-tune: true
  pretrained: bert-base-uncased
  tokenizer": bert-base-uncased
  output_dir: fine-tuned-bert-go
  warm_up_ratio: 0.0
  num_epochs: 5.0
  early_stop: false
  train_pos_dup: 2
  train_neg_dup: 2